
[Spawning]
	#This controls whether the dweller bosses (spider moth, scorpioid bloodluster, draconic voidlasher, tormentor) are included in general. Set to false if you only want the other mobs, and the dwellers will become unable to be spawned in any way.
	"Boss Inclusion" = true
	#Dwellers and variant spawns are rare by default. 1=twice as common. 2=default rarity. 3=twice as rare. 4=three times rarer.
	"Boss Rarity" = 2.0
	#This controls whether all dweller versions will require specific weather conditions to spawn. Without this, they will appear very frequently.
	"Bosses Require Weather?" = true
	#Do you want the dwellers and clone versions to spawn naturally, or only from summoning structures?
	"Boss Natural Spawning" = true
	#Controls the spawnrate of ALL non-boss mobs in this mod, including minibosses and all regular arthropods. Default multiplier value is 8. To double ArPhEx spawnrates, set it to 4. Lower values = more spawns (minimum value is 1). No maximum rarity.
	"Non-Boss ArPhEx Global Spawnrates" = 8.0

[Difficulty]
	#By default, the dweller bosses have hundreds of health points. Choose true to decrease their maximum to just 60 health.
	"Dweller Easy Mode" = false
	#Controls difficulty for ALL ArPhEx mobs, minibosses, and bosses. Affects their ranged projectiles too. Default value is 0. Positive values will give that level of strength. Negative values will give that equivalent level of weakness. E.g. To give all ArPhEx mobs permanent strength 5 (extreme difficulty!), set the value to 6, or for weakness 5, set it to -6.
	"Overall Difficulty Control" = 0.0

